### ISSUE TITLE
Error unwrapping Result<Option<CurrentlyPlaying>> from aspotify::endpoints::player::get_playing_track

### ISSUE THREAD

**Issue by tmb** [KaiJewson/aspotify#1]
I'm new to Rust so apologies in advance if I don't give enough detail.

I'm using `aspotify::endpoints::player::get_playing_track` to grab whatever song I'm currently listening to. It works fine when I'm listening to a song off of my liked songs or if I play one via search, but if I play a song off a playlist, it errors with:

```
'called `Result::unwrap()` on an `Err` value: ParseError(Error("unknown field `playlist`, there are no fields", line: 9, column: 65))'
```

I'm not totally sure what's going on here though I assume it's probably something with the way that `CurrentlyPlaying` is being parsed.

Thanks in advance for the help.

**Comment by SabrinaJewson** [comment]
This bug was due to Spotify giving me old-style playlist IDs (`spotify:user:{name}:playlist:{id}`), when I expected new-style playlist IDs (`spotify:playlist:{id}`). It's fixed now though (in 0.1.4), thanks for reporting!
