### ISSUE TITLE
Setting up explicit access token is not supported

### ISSUE THREAD

**Issue by jpochyla** [KaiJewson/aspotify#2]
Hi! In my application I talk to Spotify through the TCP mercury connection, and retrieve access tokens with a mercury call. This completely avoids authorizing apps through the Web, and client ID and secret are not used for retrieving the token. Would you be interested in a PR that separates `aspotify::Client` from the authentication mechanisms?

Thank you!

**Comment by SabrinaJewson** [comment]
Yes, that sounds useful. The simplest way to do this would probably be to make `AccessToken` public and support creating `Client`s from `AccessToken`s.

**Comment by jpochyla** [comment]
That would be the easiest way, but not strictly correct, as no `ClientCredentials` are available, really. I think I have a simple way to do this properly, but it would be a breaking change.
Edit: oof, just realized that would require an async trait. Public `AccessToken` sounds good, I'm on it!

**Comment by SabrinaJewson** [comment]
Actually my method would break because aspotify will attempt to get another token from Spotify if it expires. An async trait may be the only way.
